.TH "emuBOOB" "1" "June 16, 2021" "emuBOOB"
.SH NAME
.BR "emuBOOB" " - i8008 emulator"
.SH SYNOPSIS
.B emuBOOB
.RI "[" "SUBCOMMAND" "] [" "FLAGS" "] [" "OPTIONS" "]" "--input " "<" "INPUT_FILE" ">"
.SH OPTIONS 
.TP
.BR "-v" ", " "--version"
.R "Displaing version of zsfetch"
.TP
.BR "-e" ", " "--errors"
.R "WIthout hiding anything"
.SH AUTHOR
Written by MrZlo <zlo.alex.it@gmail.com>
